name: 🐞 Bug
description: File a bug
title: "[BUG] <title>"
labels: []
body:
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: input
  attributes:
    label: Operator version
    description: 
  validations:
    required: true
- type: input
  attributes:
    label: Installer version
    description: 
  validations:
    required: true
- type: input
  attributes:
    label: Testcase
    description: Testcase url, if one exists
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Reproduction steps, if not existing testcase
    placeholder: |
      1. How did you install
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
